### ISSUE TITLE
Group Messaging ?

### ISSUE THREAD

**Issue by EtienneDion** [blue-mantis/BM-Private-Messaging#3]
Is there a way to send message to multiple users at the time? Does the 'recipientId' field can take more than one id?

**Comment by auralon** [comment]
Hi @EtienneDion, unfortunately this functionality is not currently provided with the plugin.  The best way to handle that would be to maintain a separate table to relate users to messages in a many-to-many relationship, instead of relying on the existing recipientId property for an individual message.

It's certainly something that could be added in.  I'm not sure we'd be able to add it in in the near-future, unless it was contracted work (which we'd be happy to quote for, if you wanted).  It's perhaps worth mentioning that we would gladly accept pull requests for such functionality, if you were to build it yourself also.

**Comment by EtienneDion** [comment]
@auralon How can we get a quote on this?

**Comment by auralon** [comment]
@EtienneDion If you email me then I can send you a quote through - keith [at] bluemantis.com
